name: Project Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.14
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14'  # Spécifiez la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt avec les dépendances nécessaires

    - name: Check pytest installation
      run: pytest --version  # Vérifiez que pytest est bien installé

    - name: List files for debugging
      run: ls -R  # Liste tous les fichiers pour s'assurer que les fichiers de test sont présents

    - name: Test with pytest
      run: |
        pytest -vv || echo "Pytest failed"
