name: Project Tests

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.11.5, 3.10.13, 3.9.17, 3.8.17] #3.8.17 Test avec plusieurs versions de Python

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installer les dépendances

    - name: Check pytest installation
      run: pytest --version

    - name: List installed packages
      run: pip freeze  # Vérifier que les bonnes versions des packages sont installées

    - name: Test with pytest
      run: |
        pytest -vv test_session.py || echo "Pytest failed"
        python test_python.py
