name: Compare Julia, Python, and MATLAB Results

on:
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version

    # 3. Set up Julia
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'  # Specify the Julia version

    # 4. Set up MATLAB
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: 'R2023a'  # Specify the MATLAB release

    # 5. Run Python code
    - name: Run Python script
      run: |
        python -c "import math; print(math.sqrt(2))" > python_result.txt  # Save Python result to a file

    # 6. Run Julia code
    - name: Run Julia script
      run: |
        julia -e 'println(sqrt(2))' > julia_result.txt  # Save Julia result to a file

    # 7. Run MATLAB code
    - name: Run MATLAB script
      run: |
        matlab -batch "format long; result = sqrt(2); disp(result);" > matlab_raw.txt  # Save raw MATLAB result to a file
        grep -Eo '[0-9]+\.[0-9]+' matlab_raw.txt > matlab_result.txt  # Extract only the number from the output


    # 8. Compare the results with an absolute tolerance of 1e-15
    - name: Compare Results
      run: |
        python_result=$(cat python_result.txt)
        julia_result=$(cat julia_result.txt)
        matlab_result=$(cat matlab_result.txt)

        echo "Python result: $python_result"
        echo "Julia result: $julia_result"
        echo "MATLAB result: $matlab_result"

        abs_tol=1e-15

        # Convert results to floating point numbers
        python_result=$(echo $python_result | awk '{printf "%.16f\n", $1}')
        julia_result=$(echo $julia_result | awk '{printf "%.16f\n", $1}')
        matlab_result=$(echo $matlab_result | awk '{printf "%.16f\n", $1}')

        # Calculate absolute differences
        diff_py_julia=$(awk -v py=$python_result -v jl=$julia_result 'BEGIN {print (py>jl ? py-jl : jl-py)}')
        diff_py_matlab=$(awk -v py=$python_result -v ml=$matlab_result 'BEGIN {print (py>ml ? py-ml : ml-py)}')

        echo "Absolute difference between Python and Julia: $diff_py_julia"
        echo "Absolute difference between Python and MATLAB: $diff_py_matlab"

        # Check if the differences are within the tolerance
        if (( $(echo "$diff_py_julia < $abs_tol" | bc -l) )) && (( $(echo "$diff_py_matlab < $abs_tol" | bc -l) )); then
          echo "Results match within the absolute tolerance of $abs_tol."
        else
          echo "Results do not match within the absolute tolerance of $abs_tol!" && exit 1
        fi
